college/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include("courses.urls")),
    path('users/', include("users.urls")),
    path('', include("users.urls")),
]

courses/urls.py
from django.urls import path

from . import views

app_name="courses"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:course_id>/", views.course, name="course"),
    path("<int:course_id>/book/", views.book, name="book"),
    path("<int:course_id>/remove/", views.remove, name="remove"),
    path("<int:course_id>/godhand/", views.godhand, name="godhand"),
    
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),

]

courses/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=64)
    maxquantity = models.IntegerField()
    nowquantity = models.IntegerField(default=0)
    semester = models.IntegerField(default=None)
    year = models.IntegerField(default=None)
    students = models.ManyToManyField(User, blank=True, related_name="courses")
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id} : {self.name}"

users/models.py
from django.db import models

# Create your models here.

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.

from .models import Course

def index(request):
    return render(request, "courses/index.html", {
        "courses": Course.objects.all()
    })


def course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    return render(request, "courses/course.html", {
        "course": course,
        "students": course.students.all()
    })


def book(request, course_id):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login")
        return HttpResponseRedirect(reverse("users:login")+f"?next={request.path}")

    course = get_object_or_404(Course, pk=course_id)
    if request.user not in course.students.all():
        course.students.add(request.user)
        course = Course.objects.get(id = course_id)
        course.nowquantity += 1
        course.save()
    return HttpResponseRedirect(reverse("courses:course", args=(course_id,)))


def remove(request, course_id):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login")
        return HttpResponseRedirect(reverse("users:login")+f"?next={request.path}")

    course = get_object_or_404(Course, pk=course_id)
    if request.user in course.students.all():
        course.students.remove(request.user)
        course = Course.objects.get(id = course_id)
        course.nowquantity -= 1
        course.save()
    return HttpResponseRedirect(reverse("courses:course", args=(course_id,)))


def godhand(request, course_id):
    if request.user.is_superuser:
        course = Course.objects.get(id = course_id)
        if course.status:
            course.status = False
            course.save()
        else:
            course.status = True
            course.save()
    return HttpResponseRedirect(reverse("courses:course", args=(course_id,)))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import sys
sys.path.append('../')
from courses.models import *
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    else:
        courselist = []
        for c in Course.objects.all():
            if request.user in c.students.all():
                courselist.append(c) 
           
        return render(request, "users/index.html",{
            "courselist": courselist
        })

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            messages.warning(request, "Invalid credential.")
            return render(request, "users/login.html", {
                "messages": messages.get_messages(request)
            })
    return render(request, "users/login.html")

    

def logout_view(request):
    logout(request)
    messages.success(request, "your account has been signed off.")
    return render(request, "users/login.html", {
        "messages": messages.get_messages(request)
    })

courses/templates/courses/course.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}
<div style = "text-align: center;margin-top: 7%;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@400&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Livvic', sans-serif;
            background-color: rgb(0, 0, 0);
            color:#ffffff;
        }
    
    </style>

    <h1 class="lh12">Course {{ course.id }}</h1>
        <p class="litb">Name <span style="color:#f4a7bb">:</span> {{ course.name }}<br>
            Quota <span style="color:#f4a7bb">:</span> {{ course.maxquantity }}<br>
            Semester <span style="color:#f4a7bb">:</span> {{ course.semester }}<br>
            Years <span style="color:#f4a7bb">:</span> {{ course.year }}<br>
            {% if course.nowquantity < course.maxquantity %}
            Quota <span style="color:#f4a7bb">:</span> {{ course.nowquantity }} / {{ course.maxquantity }}<br>
            {% else %}
            Amount <span style="color:#f4a7bb">:</span> <span style="color:tomato">{{ course.nowquantity }} / {{ course.maxquantity }} &Cross;FULL&Cross;</span><br>
            {% endif %}
            {% if course.status %}
            Status <span style="color:#f4a7bb">:</span> <span style="color:#92ca91">available</span><br>
            {% else %}
            Status <span style="color:#f4a7bb">:</span> <span style="color:tomato">unavailable</span><br>
            {% if not course.status and not request.user.is_superuser %}
            <br>can't register or deregister because course is unavailable.
            {% endif %}
        </p>
        {% endif %}

    {% if request.user.is_superuser %}
        <h2 class="lh12">Students</h2>
        <p class="litbb"><span style="color:#f4a7bb">&uArr;</span>
            {% for student in students %}
            {{student.id}} : {{student.first_name}} {{student.last_name}} <span style="color:#f4a7bb">&uArr;</span>
            {% empty %}
            No students &uArr;
            {% endfor %}
        </p>
    {% endif %}
    
    {% if not request.user.is_superuser %}
        {% if course.status %}
           
        {% if request.user not in students %}
            {% if course.nowquantity < course.maxquantity %}
                <a class="rbutton rbutton1" href="{% url 'courses:book' course.id %}">register</a>
                <p class="litb" style = "color: #ffffff">Click register button to register this course.</p><br>   
            {% else %}
                <p class="litb">can't register because course is full.</p>
            {% endif %}
          
        {% else %}
        <a class="dbutton dbutton1" href="{% url 'courses:remove' course.id %}">deregister</a>
        <p class="litb"><span style="color:#92ca91">you've already registered.</span><br>
        Click deregister button to deregister this course.
        </p>   
        {% endif %}
        
        {% endif %}
    {% endif %}
    
    {% if request.user in students %}
    

    {% endif %}

        <a class="outbutton outbutton1" href="{% url 'courses:index' %}">Back to courses</a>
    {% if request.user.is_superuser %}
        <a class="outbutton outbutton1" href="{% url 'courses:godhand' course.id %}">Status switch</a>
    {% endif %}
</div>
{% endblock %}

courses/templates/courses/index.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}
    <div style = "text-align: center;margin-top: 10%;">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@400&display=swap" rel="stylesheet">
        <style>
            body {
                font-family: 'Livvic', sans-serif;
                background-color: rgb(0, 0, 0);
                color:#ffffff;
            }
        </style>
        <h1 class="lh1" style="color: #f4a7bb;">Courses</h1>
        
        {% for course in courses %}
            {% if course.status %}
                {% if course.nowquantity < course.maxquantity %}
                    <a class ="cbutton cbutton1" href="{% url 'courses:course' course.id %}">Course {{ course }}</a>
                {% else %}
                    <a class ="cfbutton cfbutton1" href="{% url 'courses:course' course.id %}">Course {{ course }}</a>
                {% endif %}
                {% else %}
                <a class ="cautton cautton1" href="{% url 'courses:course' course.id %}">Course {{ course }}</a>
            {% endif %}
        {% endfor %}
        
        <br>
                
        <a class ="outbutton outbutton1" href="{% url 'users:index' %}">Back to home</a>
    </div>
{% endblock %}

courses/templates/courses/layout.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Courses</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/index.html
{% extends "users/layout.html" %}
{% load static %}
{% block body %}
    <div style = "text-align: center;margin-top: 9%;">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@400&display=swap" rel="stylesheet">
        <style>
            body {
                font-family: 'Livvic', sans-serif;
                background-color: rgb(0, 0, 0);
                color:#ffffff;
            }
        </style>
        <h1 style="color: #f4a7bb;">Welcome<span style="color:#ffffff">,</span> {{ request.user.username }} </h1>

        {% if not request.user.is_superuser %}
        <p class="litbb">Please verify the accuracy of the data.<br>
        ID <span style="color:#f4a7bb">:</span> {{ user.id }}<br>
        Name <span style="color:#f4a7bb">:</span> {{ request.user.first_name }} {{ request.user.last_name }}<br>
        Email <span style="color:#f4a7bb">:</span> {{ request.user.email }}<br>
        <span style="color:tomato">If it's not yours , please sign out and sign in using yours again.</span></p>
        <h3 style="color: #f4a7bb;">Your registered course</h3>
        <p class="litbb">{% for c in courselist %}
        &emsp;<span style="color:#f4a7bb">&#9830;</span>&emsp;{{ c }}
        {% endfor %}&nbsp;&nbsp;&nbsp;<span style="color:#f4a7bb">&#9830;</span></p>
        {% else %}
        <img src="{% static 'images/gear2.png' %}"/>Ready for course managing.<img src="{% static 'images/gear2.png' %}"/><br>
        
        {% endif %}

    

        <a class="outbutton outbutton1" href="{% url 'users:logout' %}" >Sign out</a> <a class="outbutton outbutton1" href="{% url 'courses:index' %}">Courses</a>
    </div> 
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Users</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}
{% load static %}

    {% block body %}
    
        <div style = "text-align: center;">
            {% if messages %}
                {% for message in messages %}
                    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            {% endif %}
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@400&display=swap" rel="stylesheet">
            <style>
            body {
                font-family: 'Livvic', sans-serif;
                background-color: rgb(0, 0, 0);
            }
            </style>

            <form style ="margin-top: 15%;" action="{% url 'users:login' %}?next={{ next }}" method="post">
                {% csrf_token %}
                <input class="unapw unapw1" type="text" name="username" placeholder="username"><br><br>
                <input class="unapw unapw1" type="password" name="password" placeholder="password"><br><br>
                <input class="button button1" type="submit" value="Sign in">
            </form>
        
        </div> 
        

    {% endblock %}

    